kind: "VerificationTemplate"
name: "prometheus-vt"
metrics:
  - name: "verification-background"
    interval: "10s"
    count: 6
    failureCondition: "result[0] >= 90"
    failureLimit: 3
    provider:
      prometheus:
        query: "sum(container_cpu_usage_seconds_total{namespace=\"test\"}"