apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spot-oceancd-operator-manager-clusterrole
  labels:
    app: spot-oceancd-operator-manager
    {{- include "spot-oceancd-operator-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  - services
  - secrets/finalizer
  - secrets/status
  - events
  - events/finalizers
  - events/status
  - services
  - services/finalizers
  - services/status
  - pods
  - pods/finalizers
  - pods/status
  - pods/eviction
  - namespaces
  - namespaces/finalizers
  - namespaces/status
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  - ""
  resources:
  - deployments
  - deployments/finalizers
  - deployments/status
  - replicasets
  - replicasets/finalizers
  - replicasets/status
  - podtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - analysisruns
  - analysisruns/finalizers
  - analysisruns/status
  - analysistemplates
  - analysistemplates/finalizers
  - analysistemplates/status
  - clusteranalysistemplates
  - clusteranalysistemplates/finalizers
  - clusteranalysistemplates/status
  - experiments
  - experiments/finalizers
  - experiments/status
  - rollouts
  - rollouts/finalizers
  - rollouts/status
  - rollouts/scale
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - monitoring.coreos.com/v1
  resources:
  - servicemonitors
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - networking.k8s.io/v1
  resources:
  - ingresses
  verbs:
  - create
  - get
  - list
  - watch
  - patch
- apiGroups:
  - policy/v1
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - deletecollection
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spot.io
  resources:
  - spotdeployments
  - spotdeployments/finalizers
  - spotdeployments/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
  - list
  - watch
  - patch
  - delete
- apiGroups:
  - networking.k8s.io
  - extensions
  resources:
  - ingresses
  verbs:
  - create
  - get
  - list
  - watch
  - patch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  - destinationrules
  verbs:
  - watch
  - get
  - update
  - patch
  - list
- apiGroups:
  - split.smi-spec.io
  resources:
  - trafficsplits
  verbs:
  - create
  - watch
  - get
  - update
  - patch
- apiGroups:
  - getambassador.io
  - x.getambassador.io
  resources:
  - mappings
  - ambassadormappings
  verbs:
  - create
  - watch
  - get
  - update
  - list
  - delete
- apiGroups:
  - elbv2.k8s.aws
  resources:
  - targetgroupbindings
  verbs:
  - list
  - get
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - virtualservices
  verbs:
  - watch
  - get
  - list
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - virtualnodes
  - virtualrouters
  verbs:
  - watch
  - get
  - list
  - update
  - patch
- apiGroups:
  - traefik.containo.us
  resources:
  - traefikservices
  verbs:
  - watch
  - get
  - update
- apiGroups:
  - apisix.apache.org
  resources:
  - apisixroutes
  verbs:
  - watch
  - get
  - update
- apiGroups:
  - operators.coreos.com
  resources:
  - installplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - installplans/finalizers
  verbs:
  - update
- apiGroups:
  - operators.coreos.com
  resources:
  - installplans/status
  verbs:
  - get
  - patch
  - update