apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spot-oceancd-operator-manager.fullname" . }}
  labels:
    app: spot-oceancd-operator-manager
    {{- include "spot-oceancd-operator-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  - services
  - secrets/finalizers
  - secrets/status
  - events
  - events/finalizers
  - events/status
  - services
  - services/finalizers
  - services/status
  - pods
  - pods/finalizers
  - pods/status
  - namespaces
  - namespaces/finalizers
  - namespaces/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/finalizers
  - deployments/status
  - replicasets
  - replicasets/finalizers
  - replicasets/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - analysisruns
  - analysisruns/finalizers
  - analysisruns/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - analysistemplates
  - analysistemplates/finalizers
  - analysistemplates/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - clusteranalysistemplates
  - clusteranalysistemplates/finalizers
  - clusteranalysistemplates/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - experiments
  - experiments/finalizers
  - experiments/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - rollouts
  - rollouts/finalizers
  - rollouts/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - monitoring.coreos.com/v1
  resources:
  - servicemonitors
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - networking.k8s.io/v1
  resources:
  - ingresses
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - policy/v1
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spot.io
  resources:
  - spotdeployments
  - spotdeployments/finalizers
  - spotdeployments/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
