{{- if .Values.operatorManager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spot-oceancd-operator-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: spot-oceancd-operator-manager
    {{- include "spot-oceancd-operator-manager.labels" . | nindent 4 }}
  {{- with .Values.operatorManager.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}