argoRollouts:

  # -- (Optional) If create argo-rollouts
  create: true

  # -- (Optional) If keep argo-rollouts crds
  keepCRDs: true

  # -- (Optional) If create argo-rollouts namespace
  createNamespace: true

  serviceAccount:

    # -- (Optional) Service Account Annotations
    annotations: {}

  deployment:

    # -- (Optional) Additional command line arguments to pass to rollouts-controller.  A list of flags.
    extraArgs: []

    # -- (Optional) Security Context to set on container level
    containerSecurityContext: {}

    # -- (Optional) Resource limits and requests for the argo rollouts controller pods.
    resources: {}
    #  limits:
    #    cpu: 100m
    #    memory: 128Mi
    #  requests:
    #    cpu: 50m
    #    memory: 64Mi

    # -- (Optional) Security Context to set on pod level
    podSecurityContext:
      runAsNonRoot: true

    # -- (Optional) Node selector
    nodeSelector: {}

    # -- (Optional) Tolerations for use with node taints
    tolerations: []

    # -- (Optional) Assign custom [affinity] rules to the argo rollout deployment
    affinity: {}


operator:

  # -- (Optional) List of Environment Variables that must exist in all containers in the Pod created by OLM.
  env: []

  # -- (Optional) List of sources to populate Environment Variables in the container.
  envFrom: []

  # -- (Optional) List of Volumes that must exist on the Pod created by OLM.
  volumes: []

   # -- (Optional) list of VolumeMounts that must exist in all containers in the Pod created by OLM.
  volumeMounts: []

  # -- (Optional) Tolerations for the Pod created by OLM.
  tolerations: []

  # -- (Optional) Resource limits and requests for the pod created by OLM.
  resources: {}

  # -- (Optional) Node selector for the pod created by OLM
  nodeSelector: {}

# -- (Optional) Spot token
token: ""

# -- (Optional) Use existing Secret which stores spot token. The value should be set with the `spot-token` key inside the secret.
## If set, this parameter takes precedence over "token".
tokenExistingSecret: ""

# -- (Optional) Saas URL
saasUrl: https://cluster-gateway.oceancd.io

# -- (Optional) Spot Api URL
apiUrl: https://api.spotinst.io

# -- (Required) Cluster ID
clusterId: ""

# -- (Optional) Operator Catalog channel
channel: "stable"
