apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: spot-oceancd-operator-subscription
spec:
  channel: {{ .Values.channel }}
  name: spot-oceancd-operator
  source: spot-oceancd-catalog
  sourceNamespace: {{ .Release.Namespace }}
  config:
    env:
    {{- with .Values.operator.env }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    envFrom:
    {{- with .Values.operator.envFrom }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    volumes:
    {{- with .Values.operator.volumes }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    volumeMounts:
    {{- with .Values.operator.volumeMounts }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    tolerations:
    {{- with .Values.operator.tolerations }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    resources:
    {{- with .Values.operator.resources }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    nodeSelector:
    {{- with .Values.operator.nodeSelector }}
      {{- toYaml . | nindent 6 }}
    {{- end }}