apiVersion: batch/v1
kind: Job
metadata:
  name: spot-oceancd-operator-token-generator
  labels:
    app: spot-oceancd-operator-token-generator
    {{- include "spot-oceancd-operator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  template:
    spec:
      containers:
        - name: spot-oceancd-operator-token-generator
          image: spotinst/spot-oceancd-controller-installer:helm
          imagePullPolicy: Always
          env:
            - name: API_URL
              value: {{ required "A value must be entered for apiUrl" .Values.apiUrl }}
            - name: CLUSTER_ID
              value: {{ required "A value must be entered for clusterId" .Values.clusterId }}
            {{ if .Values.token -}}
            - name: TOKEN
              value: {{ .Values.token }}
            {{ else -}}
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name:  {{ required "A value must be entered for token or tokenExistingSecret" .Values.tokenExistingSecret }}
                  key: spot-token
            {{ end }}
            - name: SAAS_URL
              value: {{ required "A value must be entered for saasUrl" .Values.saasUrl }}
      restartPolicy: Never
  backoffLimit: 1
