operatorManager:
  replicas: 1
  deploymentAnnotations: {}
  podAnnotations: {}
  podLabels: {}
  imagePullSecrets: []
  image:
    registry: ""
    repository: ""
    tag: ""
    pullPolicy: ""
  extraEnv: []
  containerPorts:
    http: 8080
  livenessProbe: {}
  readinessProbe: {}
  containerSecurityContext: {}
  resources: {}
  extraVolumeMounts: []
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  tolerations: []
  affinity: {}
  topologySpreadConstraints: []
  priorityClassName: ""
  extraVolumes: []
  serviceAccount:
    create: true
    annotations: {}
    name: ""

  token: ""

  tokenExistingSecret: ""

  saasUrl: https://cluster-gateway.oceancd.io

  apiUrl: https://api.spotinst.io

  clusterId: ""

operator:
  nodeSelector: {}
  affinity: {}
  resources: {}
  tolerations: []
  extraEnv: []
  labels: {}
  imagePullSecrets: []
  keepCRDs: true
  annotations: {}
  serviceAccountAnnotations: {}

argoRollouts:
  general:
    podLabels: {}
    podAnnotations: {}
    serviceLabels: {}
    serviceAnnotations: {}
    labels: {}
    installCRDs: true
    keepCRDs: true
  controller:
    nodeSelector: {}
    affinity: {}
    resources: {}
    tolerations: []
    extraEnv: []
    extraArgs: []
    containerSecurityContext: {}
    imagePullSecrets: []
    livenessProbe:
      httpGet:
        path: /healthz
        port: healthz
      initialDelaySeconds: 30
      periodSeconds: 20
      failureThreshold: 3
      successThreshold: 1
      timeoutSeconds: 10
    readinessProbe:
      httpGet:
        path: /metrics
        port: metrics
      initialDelaySeconds: 15
      periodSeconds: 5
      failureThreshold: 3
      successThreshold: 1
      timeoutSeconds: 4

  dashboard:
    enabled: false
    nodeSelector: {}
    affinity: {}
    resources: {}
    tolerations: []
    extraEnv: []
    containerSecurityContext: {}
    imagePullSecrets: []
