operatorManager:
  replicas: 1
  deploymentAnnotations: {}
  podAnnotations: {}
  podLabels: {}
  imagePullSecrets: []
  image:
    registry: "spotinst"
    repository: "oceancd-operator-manager"
    tag: "0.1.0"
    pullPolicy: "IfNotPresent"

  manager:
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8084
      initialDelaySeconds: 15
      periodSeconds: 20
      successThreshold: 1
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /readyz
        port: 8084
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
    containerSecurityContext:
      allowPrivilegeEscalation: false
    resources: {}
    extraVolumeMounts: []
  installation:
    resources: {}
    extraVolumeMounts: []
  regestration:
    resources: {}
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  tolerations: []
  affinity: {}
  topologySpreadConstraints: []
  priorityClassName: ""
  extraVolumes: []
  serviceAccount:
    create: true
    annotations: {}
    name: ""

  token: ""

  tokenExistingSecret: ""

  saasUrl: https://cluster-gateway.oceancd.io

  apiUrl: https://api.spotinst.io

  clusterId: ""

operator:
  namespace: oceancd
  nodeSelector: {}
  affinity: {}
  resources: {}
  tolerations: []
  extraEnv: []
  labels: {}
  imagePullSecrets: []
  annotations: {}
  serviceAccountAnnotations: {}

argoRollouts:
  general:
    namespace: argo-rollouts
    podLabels: {}
    podAnnotations: {}
    serviceLabels: {}
    serviceAnnotations: {}
    labels: {}
  controller:
    replicas: 1
    nodeSelector: {}
    affinity: {}
    resources: {}
    tolerations: []
    extraEnv: []
    extraArgs: []
    containerSecurityContext: {}
    imagePullSecrets: []
    livenessProbe:
      httpGet:
        path: /healthz
        port: healthz
      initialDelaySeconds: 30
      periodSeconds: 20
      failureThreshold: 3
      successThreshold: 1
      timeoutSeconds: 10
    readinessProbe:
      httpGet:
        path: /metrics
        port: metrics
      initialDelaySeconds: 15
      periodSeconds: 5
      failureThreshold: 3
      successThreshold: 1
      timeoutSeconds: 4

  dashboard:
    enabled: false
    replicas: 1
    nodeSelector: {}
    affinity: {}
    resources: {}
    tolerations: []
    extraEnv: []
    containerSecurityContext: {}
    imagePullSecrets: []
