apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spot-oceancd-operator-manager-role
  labels:
    app: spot-oceancd-operator-manager
    {{- include "spot-oceancd-operator-manager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["*"]