apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spot-oceancd-operator-manager-rolebinding
  labels:
    app: spot-oceancd-operator-manager
    {{- include "spot-oceancd-operator-manager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spot-oceancd-operator-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}