apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: rollout-destrule
spec:
  host: stable-service-headers
  subsets:
    - name: canary
      labels:
        app: rollout-headers-test
    - name: stable
      labels:
        app: rollout-headers-test