apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-host-split-gateway
  namespace: headers-demo
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - demo-header.example.com
      port:
        name: http
        number: 80
        protocol: HTTP