name: "Strategy-Verification-Prometheus"
canary:
  backgroundVerification:
    templateNames:
      - "prometheus-vt"
  steps:
    - name: "set-weight-1"
      setWeight: 20
    - name: "set-weight-2"
      setWeight: 40
      pause:
        duration: 1m
    - name: "set-weight-3"
      setWeight: 60
    - name: "set-weight-4"
      setWeight: 80
    - name: "set-weight-final"
      setWeight: 100